version: '3.8'

services:
  database-visualization:
    image: database-visualization-container
    container_name: database-visualization-container
    networks:
      - microservices

  test-visualization:
    image: test-visualization
    depends_on:
      - database-visualization
    networks:
      - microservices

networks:
  microservices:
    driver: bridge