name: Run tests

on: ["push", "pull_request"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5.1.0
      - name: Install dependencieds
        run: pip install -r tests/requirements.txt
      - name: Run tests
        run: pytest tests/test_date_utils.py -v
