name: Test container deployment

on: ["push", "pull_request"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5.1.0
      - name: Run all containers
        run: ./run_containers.sh
      - name: Install dependencies
        run: pip install -r tests/requirements.txt
      - name: Test container endpoints
        run: pytest tests/test_containers_endpoints.py -v
